name: working-dir-and-shells
on: 
  push:
jobs:
  linux-job:
    runs-on: ubuntu-latest
    steps:
      - name: display-working-dir-and-list-files
        run: |
             pwd
             ls
             echo $GITHUB_SHA
             echo $GITHUN_REPOSITORY
             evho $GITHUB_WORKSPACE
  windows-job:
    runs-on: ubuntu-latest
    steps:
      - name: display-working-dir-and-list-files
        run: |
             pwd
             ls
             echo $GITHUB_SHA
             echo $GITHUN_REPOSITORY
             evho $GITHUB_WORKSPACE